@base = http://localhost:3000
@json = application/json
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZWNmNzE2YS1hYTg5LTQxNmMtOTc1YS03MzNkZGY5MzY2OTQiLCJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJpYXQiOjE3NTg4MDY4MzQsImV4cCI6MTc1ODgxNDAzNH0.ijN8g5aTlUgcIz-gXDxhrFnsn5mrtXp4zx68KRBp7SU
###
#Login (ejecuta, copia el token y pégalo arriba en @token)
POST {{base}}/api/auth/login
Content-Type: {{json}}

{
"email": "test@example.com",
"password": "secret123"
}
###

#Entradas (protegido)
GET {{base}}/api/entries
Authorization: Bearer {{token}}
###

#Crear entrada (protegido) – recuerda usar un foodId real
POST {{base}}/api/entries
Content-Type: {{json}}
Authorization: Bearer {{token}}

{
"foodId": "aa072b8c-f8cd-4c30-a279-be76ea92c84f",
"grams": 150
}
###

#Goals (protegido)
GET {{base}}/api/users/me/goals
Authorization: Bearer {{token}}
###
PUT {{base}}/api/users/me/goals
Content-Type: {{json}}
Authorization: Bearer {{token}}

{
"calories": 2200
}
###
GET {{base}}/api/foods